name: project-linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-config:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.10.12]
        poetry-version: [1.8.4]
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      - name: Poetry setup
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{matrix.poetry-version}}
      - name: Install dependencies for linting
        run: poetry install --with dev,test
  linting:
      needs: setup-config
      runs-on: ubuntu-latest
      steps:
        - name: Run the ruff with the toml file.
          run: poetry run ruff check --config ruff.toml
  code-security:
      needs: setup-config
      runs-on: ubuntu-latest
      steps:
        - name: Check for common security issues
          run: poetry run bandit .