name: project-linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-quality:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.10.12]
        poetry-version: [1.8.4]
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      - name: Poetry setup
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{matrix.poetry-version}}
      - name: Install dependencies
        run: poetry install --with dev
      - name: Run the ruff with the toml file.
        run: poetry run ruff check --config ruff.toml
      - name: Check for common security issues
        run: poetry run bandit .